name: charactergen
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - ipywidgets
  - pylint
  - rope
  - nodejs
  - pillow
  - scrapy
  - pytorch>=1.7.1
  - torchvision
  - fastai>=2.2.5
  - matplotlib
  - wandb
  - pip
  - pip:
    - pytorch-lightning
