name: charactergen
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - ipywidgets
  - pylint
  - rope
  - nodejs
  - pillow
  - scrapy
  - pytorch>=1.7.1
  - torchvision
  - matplotlib
